name: Jest tests

on: 
  pull_request:
  push:
    branches:
      - main
    
jobs:
  test-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test